version: 2

models:
  - name: stg_crm_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
      - name: employee_count
        tests: [not_null]
      - name: acquisition_channel
        tests:
          - accepted_values:
              values: ['inbound', 'outbound', 'partner', 'events', 'referral']

  - name: stg_crm_opportunities
    columns:
      - name: opp_id
        tests: [not_null, unique]
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_crm_accounts')
              field: account_id
      - name: stage
        tests:
          - accepted_values:
              values: ['Closed Won', 'Closed Lost']
      - name: source_channel
        tests:
          - accepted_values:
              values: ['inbound', 'outbound', 'partner', 'events', 'referral']

  - name: stg_billing_contracts
    columns:
      - name: contract_id
        tests: [not_null, unique]
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_crm_accounts')
              field: account_id
      - name: product_bundle
        tests:
          - accepted_values:
              values: ['Payroll Only', 'Payroll+Time', 'Payroll+Time+Benefits', 'Full HCM']

  - name: stg_billing_invoices
    columns:
      - name: invoice_id
        tests: [not_null, unique]
      - name: contract_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_billing_contracts')
              field: contract_id
      - name: status
        tests:
          - accepted_values:
              values: ['Paid', 'Past Due']

  - name: stg_product_usage_daily
    columns:
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_crm_accounts')
              field: account_id
      - name: usage_date
        tests: [not_null]

  - name: stg_support_tickets
    columns:
      - name: ticket_id
        tests: [not_null, unique]
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_crm_accounts')
              field: account_id
      - name: severity
        tests:
          - accepted_values:
              values: ['Low', 'Med', 'High', 'Sev1']
  - name: stg_marketing_campaigns
    columns:
      - name: campaign_id
        tests: [not_null, unique]
      - name: channel
        tests:
          - accepted_values:
              values: ['paid_search','paid_social','webinar','content','events','partner_marketing']

  - name: stg_marketing_spend_daily
    columns:
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_marketing_campaigns')
              field: campaign_id
      - name: spend_usd
        tests: [not_null]

  - name: stg_marketing_leads
    columns:
      - name: lead_id
        tests: [not_null, unique]
      - name: campaign_id
        tests:
          - relationships:
              to: ref('stg_marketing_campaigns')
              field: campaign_id

  - name: stg_marketing_touches
    columns:
      - name: touch_id
        tests: [not_null, unique]
      - name: lead_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_marketing_leads')
              field: lead_id
      - name: touch_type
        tests:
          - accepted_values:
              values: ['email','ad_click','web_visit','webinar_attended','event_booth','demo_request']

  - name: stg_crm_opportunity_stage_history
    columns:
      - name: stage_event_id
        tests: [not_null, unique]
      - name: opp_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_crm_opportunities')
              field: opp_id
